# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03eaab196cb6c3e70821914473299bd834534316012b029f1873526e11655f2c902f962c1c39359a25a6aed7b4b6a6d72c33c146fe69e44146bead150879066f

test:
  secret_key_base: 1bb165318e4fb78984786ce7b92becabffef7f9d2095b61980f8a295f15d9bd6ff26cc9d8d324301eb3ec915f1fa127ac0e2a420a0cd57c6cb27c2fad4e67288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
